version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'qr-seat-reservation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./app-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amithfernando/qr-seat-reservation:latest
    environment:
      DB_URL: jdbc:mysql://db:3306/qr-seat-reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: user
      DB_PWD: password
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
volumes:
  app-db: