/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.api;

import com.amithfernando.qrseatreservation.client.model.ErrorResponse;
import com.amithfernando.qrseatreservation.client.model.Setting;
import com.amithfernando.qrseatreservation.client.model.UpdateSettingRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SettingsApi
 */
@Ignore
public class SettingsApiTest {

    private final SettingsApi api = new SettingsApi();

    
    /**
     * Get current settings
     *
     * Retrieves the current application settings
     */
    @Test
    public void getSettingsTest()  {
        Setting response = api.getSettings().block();

        // TODO: test validations
    }
    
    /**
     * Update settings
     *
     * Updates the application settings. All fields are optional - only provided fields will be updated.
     */
    @Test
    public void updateSettingsTest()  {
        UpdateSettingRequest updateSettingRequest = null;
        Setting response = api.updateSettings(updateSettingRequest).block();

        // TODO: test validations
    }
    
}
