/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Check-in statistics
 */
@JsonPropertyOrder({
  CheckInStats.JSON_PROPERTY_TOTAL_CHECKED_IN,
  CheckInStats.JSON_PROPERTY_TOTAL_RESERVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CheckInStats implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL_CHECKED_IN = "totalCheckedIn";
  private Long totalCheckedIn;

  public static final String JSON_PROPERTY_TOTAL_RESERVED = "totalReserved";
  private Long totalReserved;

  public CheckInStats() {
  }

  public CheckInStats totalCheckedIn(Long totalCheckedIn) {
    
    this.totalCheckedIn = totalCheckedIn;
    return this;
  }

   /**
   * Total number of checked-in tickets
   * @return totalCheckedIn
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalCheckedIn() {
    return totalCheckedIn;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalCheckedIn(Long totalCheckedIn) {
    this.totalCheckedIn = totalCheckedIn;
  }


  public CheckInStats totalReserved(Long totalReserved) {
    
    this.totalReserved = totalReserved;
    return this;
  }

   /**
   * Total number of reserved (not checked-in) tickets
   * @return totalReserved
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_RESERVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalReserved() {
    return totalReserved;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_RESERVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalReserved(Long totalReserved) {
    this.totalReserved = totalReserved;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckInStats checkInStats = (CheckInStats) o;
    return Objects.equals(this.totalCheckedIn, checkInStats.totalCheckedIn) &&
        Objects.equals(this.totalReserved, checkInStats.totalReserved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCheckedIn, totalReserved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckInStats {\n");
    sb.append("    totalCheckedIn: ").append(toIndentedString(totalCheckedIn)).append("\n");
    sb.append("    totalReserved: ").append(toIndentedString(totalReserved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

