/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Response after checking in a ticket
 */
@JsonPropertyOrder({
  CheckInResponse.JSON_PROPERTY_SUCCESS,
  CheckInResponse.JSON_PROPERTY_TICKET_NO,
  CheckInResponse.JSON_PROPERTY_MESSAGE,
  CheckInResponse.JSON_PROPERTY_SEAT_NO,
  CheckInResponse.JSON_PROPERTY_TABLE_NAME,
  CheckInResponse.JSON_PROPERTY_SELLER_NAME,
  CheckInResponse.JSON_PROPERTY_CHECKED_IN_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CheckInResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SUCCESS = "success";
  private Boolean success;

  public static final String JSON_PROPERTY_TICKET_NO = "ticketNo";
  private String ticketNo;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  private String seatNo;

  public static final String JSON_PROPERTY_TABLE_NAME = "tableName";
  private String tableName;

  public static final String JSON_PROPERTY_SELLER_NAME = "sellerName";
  private String sellerName;

  public static final String JSON_PROPERTY_CHECKED_IN_AT = "checkedInAt";
  private OffsetDateTime checkedInAt;

  public CheckInResponse() {
  }

  public CheckInResponse success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Whether check-in was successful
   * @return success
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public CheckInResponse ticketNo(String ticketNo) {
    
    this.ticketNo = ticketNo;
    return this;
  }

   /**
   * Ticket number that was checked in
   * @return ticketNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketNo() {
    return ticketNo;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketNo(String ticketNo) {
    this.ticketNo = ticketNo;
  }


  public CheckInResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Message describing the result
   * @return message
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public CheckInResponse seatNo(String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

   /**
   * Seat number
   * @return seatNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNo(String seatNo) {
    this.seatNo = seatNo;
  }


  public CheckInResponse tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Table name
   * @return tableName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  public CheckInResponse sellerName(String sellerName) {
    
    this.sellerName = sellerName;
    return this;
  }

   /**
   * Seller name
   * @return sellerName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SELLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSellerName() {
    return sellerName;
  }


  @JsonProperty(JSON_PROPERTY_SELLER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSellerName(String sellerName) {
    this.sellerName = sellerName;
  }


  public CheckInResponse checkedInAt(OffsetDateTime checkedInAt) {
    
    this.checkedInAt = checkedInAt;
    return this;
  }

   /**
   * Check-in timestamp
   * @return checkedInAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CHECKED_IN_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCheckedInAt() {
    return checkedInAt;
  }


  @JsonProperty(JSON_PROPERTY_CHECKED_IN_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckedInAt(OffsetDateTime checkedInAt) {
    this.checkedInAt = checkedInAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckInResponse checkInResponse = (CheckInResponse) o;
    return Objects.equals(this.success, checkInResponse.success) &&
        Objects.equals(this.ticketNo, checkInResponse.ticketNo) &&
        Objects.equals(this.message, checkInResponse.message) &&
        Objects.equals(this.seatNo, checkInResponse.seatNo) &&
        Objects.equals(this.tableName, checkInResponse.tableName) &&
        Objects.equals(this.sellerName, checkInResponse.sellerName) &&
        Objects.equals(this.checkedInAt, checkInResponse.checkedInAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, ticketNo, message, seatNo, tableName, sellerName, checkedInAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckInResponse {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    ticketNo: ").append(toIndentedString(ticketNo)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    sellerName: ").append(toIndentedString(sellerName)).append("\n");
    sb.append("    checkedInAt: ").append(toIndentedString(checkedInAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

