/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
/**
 * CreateTableRequest
 */
@JsonPropertyOrder({
  CreateTableRequest.JSON_PROPERTY_TABLE_NAME,
  CreateTableRequest.JSON_PROPERTY_NO_OF_AVAILABLE_SEATS,
  CreateTableRequest.JSON_PROPERTY_NO_OF_UNAVAILABLE_SEATS,
  CreateTableRequest.JSON_PROPERTY_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateTableRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TABLE_NAME = "tableName";
  private String tableName;

  public static final String JSON_PROPERTY_NO_OF_AVAILABLE_SEATS = "noOfAvailableSeats";
  private Integer noOfAvailableSeats;

  public static final String JSON_PROPERTY_NO_OF_UNAVAILABLE_SEATS = "noOfUnavailableSeats";
  private Integer noOfUnavailableSeats;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public CreateTableRequest() {
  }

  public CreateTableRequest tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Get tableName
   * @return tableName
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  public CreateTableRequest noOfAvailableSeats(Integer noOfAvailableSeats) {
    
    this.noOfAvailableSeats = noOfAvailableSeats;
    return this;
  }

   /**
   * Get noOfAvailableSeats
   * minimum: 1
   * maximum: 20
   * @return noOfAvailableSeats
  **/
  @jakarta.annotation.Nullable
 @Min(1) @Max(20)
  @JsonProperty(JSON_PROPERTY_NO_OF_AVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfAvailableSeats() {
    return noOfAvailableSeats;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_AVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfAvailableSeats(Integer noOfAvailableSeats) {
    this.noOfAvailableSeats = noOfAvailableSeats;
  }


  public CreateTableRequest noOfUnavailableSeats(Integer noOfUnavailableSeats) {
    
    this.noOfUnavailableSeats = noOfUnavailableSeats;
    return this;
  }

   /**
   * Get noOfUnavailableSeats
   * minimum: 1
   * maximum: 20
   * @return noOfUnavailableSeats
  **/
  @jakarta.annotation.Nullable
 @Min(1) @Max(20)
  @JsonProperty(JSON_PROPERTY_NO_OF_UNAVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfUnavailableSeats() {
    return noOfUnavailableSeats;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_UNAVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfUnavailableSeats(Integer noOfUnavailableSeats) {
    this.noOfUnavailableSeats = noOfUnavailableSeats;
  }


  public CreateTableRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTableRequest createTableRequest = (CreateTableRequest) o;
    return Objects.equals(this.tableName, createTableRequest.tableName) &&
        Objects.equals(this.noOfAvailableSeats, createTableRequest.noOfAvailableSeats) &&
        Objects.equals(this.noOfUnavailableSeats, createTableRequest.noOfUnavailableSeats) &&
        Objects.equals(this.description, createTableRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tableName, noOfAvailableSeats, noOfUnavailableSeats, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTableRequest {\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    noOfAvailableSeats: ").append(toIndentedString(noOfAvailableSeats)).append("\n");
    sb.append("    noOfUnavailableSeats: ").append(toIndentedString(noOfUnavailableSeats)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

