/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.amithfernando.qrseatreservation.client.model.SeatReservationItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Request object for creating a new reservation
 */
@JsonPropertyOrder({
  CreateReservationRequest.JSON_PROPERTY_SELLER_ID,
  CreateReservationRequest.JSON_PROPERTY_SEAT_RESERVATIONS,
  CreateReservationRequest.JSON_PROPERTY_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateReservationRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SELLER_ID = "sellerId";
  private Long sellerId;

  public static final String JSON_PROPERTY_SEAT_RESERVATIONS = "seatReservations";
  private List<@Valid SeatReservationItem> seatReservations = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public CreateReservationRequest() {
  }

  public CreateReservationRequest sellerId(Long sellerId) {
    
    this.sellerId = sellerId;
    return this;
  }

   /**
   * ID of the seller making the reservation
   * @return sellerId
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SELLER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSellerId() {
    return sellerId;
  }


  @JsonProperty(JSON_PROPERTY_SELLER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSellerId(Long sellerId) {
    this.sellerId = sellerId;
  }


  public CreateReservationRequest seatReservations(List<@Valid SeatReservationItem> seatReservations) {
    
    this.seatReservations = seatReservations;
    return this;
  }

  public CreateReservationRequest addSeatReservationsItem(SeatReservationItem seatReservationsItem) {
    if (this.seatReservations == null) {
      this.seatReservations = new ArrayList<>();
    }
    this.seatReservations.add(seatReservationsItem);
    return this;
  }

   /**
   * List of seat reservations with their ticket types
   * @return seatReservations
  **/
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT_RESERVATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<@Valid SeatReservationItem> getSeatReservations() {
    return seatReservations;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_RESERVATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatReservations(List<@Valid SeatReservationItem> seatReservations) {
    this.seatReservations = seatReservations;
  }


  public CreateReservationRequest description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Optional description or notes for the reservation
   * @return description
  **/
  @jakarta.annotation.Nullable
 @Size(min=0,max=500)
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReservationRequest createReservationRequest = (CreateReservationRequest) o;
    return Objects.equals(this.sellerId, createReservationRequest.sellerId) &&
        Objects.equals(this.seatReservations, createReservationRequest.seatReservations) &&
        Objects.equals(this.description, createReservationRequest.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sellerId, seatReservations, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReservationRequest {\n");
    sb.append("    sellerId: ").append(toIndentedString(sellerId)).append("\n");
    sb.append("    seatReservations: ").append(toIndentedString(seatReservations)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

