/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.amithfernando.qrseatreservation.client.model.SeatReservationInfo;
import com.amithfernando.qrseatreservation.client.model.SellerInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Reservation response with all details
 */
@JsonPropertyOrder({
  ReservationResponse.JSON_PROPERTY_ID,
  ReservationResponse.JSON_PROPERTY_REFERENCE_NO,
  ReservationResponse.JSON_PROPERTY_SELLER,
  ReservationResponse.JSON_PROPERTY_SEAT_RESERVATIONS,
  ReservationResponse.JSON_PROPERTY_DESCRIPTION,
  ReservationResponse.JSON_PROPERTY_STATUS,
  ReservationResponse.JSON_PROPERTY_CREATED_AT,
  ReservationResponse.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ReservationResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_REFERENCE_NO = "referenceNo";
  private String referenceNo;

  public static final String JSON_PROPERTY_SELLER = "seller";
  private SellerInfo seller;

  public static final String JSON_PROPERTY_SEAT_RESERVATIONS = "seatReservations";
  private List<@Valid SeatReservationInfo> seatReservations;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  /**
   * Reservation status
   */
  public enum StatusEnum {
    PAYMENT_PENDING("PAYMENT_PENDING"),
    
    PAID("PAID"),
    
    CHECKED_IN("CHECKED_IN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public ReservationResponse() {
  }

  public ReservationResponse id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Reservation ID
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public ReservationResponse referenceNo(String referenceNo) {
    
    this.referenceNo = referenceNo;
    return this;
  }

   /**
   * Unique reference number
   * @return referenceNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReferenceNo() {
    return referenceNo;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceNo(String referenceNo) {
    this.referenceNo = referenceNo;
  }


  public ReservationResponse seller(SellerInfo seller) {
    
    this.seller = seller;
    return this;
  }

   /**
   * Seller information
   * @return seller
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SellerInfo getSeller() {
    return seller;
  }


  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeller(SellerInfo seller) {
    this.seller = seller;
  }


  public ReservationResponse seatReservations(List<@Valid SeatReservationInfo> seatReservations) {
    
    this.seatReservations = seatReservations;
    return this;
  }

  public ReservationResponse addSeatReservationsItem(SeatReservationInfo seatReservationsItem) {
    if (this.seatReservations == null) {
      this.seatReservations = new ArrayList<>();
    }
    this.seatReservations.add(seatReservationsItem);
    return this;
  }

   /**
   * List of reserved seats
   * @return seatReservations
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT_RESERVATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid SeatReservationInfo> getSeatReservations() {
    return seatReservations;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_RESERVATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatReservations(List<@Valid SeatReservationInfo> seatReservations) {
    this.seatReservations = seatReservations;
  }


  public ReservationResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Reservation description
   * @return description
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ReservationResponse status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Reservation status
   * @return status
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public ReservationResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation timestamp
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ReservationResponse updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Last update timestamp
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReservationResponse reservationResponse = (ReservationResponse) o;
    return Objects.equals(this.id, reservationResponse.id) &&
        Objects.equals(this.referenceNo, reservationResponse.referenceNo) &&
        Objects.equals(this.seller, reservationResponse.seller) &&
        Objects.equals(this.seatReservations, reservationResponse.seatReservations) &&
        Objects.equals(this.description, reservationResponse.description) &&
        Objects.equals(this.status, reservationResponse.status) &&
        Objects.equals(this.createdAt, reservationResponse.createdAt) &&
        Objects.equals(this.updatedAt, reservationResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, referenceNo, seller, seatReservations, description, status, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReservationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    referenceNo: ").append(toIndentedString(referenceNo)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    seatReservations: ").append(toIndentedString(seatReservations)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

