/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Seat reservation information
 */
@JsonPropertyOrder({
  SeatReservationInfo.JSON_PROPERTY_SEAT_ID,
  SeatReservationInfo.JSON_PROPERTY_SEAT_NO,
  SeatReservationInfo.JSON_PROPERTY_TABLE_NAME,
  SeatReservationInfo.JSON_PROPERTY_TICKET_NO,
  SeatReservationInfo.JSON_PROPERTY_TICKET_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SeatReservationInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SEAT_ID = "seatId";
  private Long seatId;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  private String seatNo;

  public static final String JSON_PROPERTY_TABLE_NAME = "tableName";
  private String tableName;

  public static final String JSON_PROPERTY_TICKET_NO = "ticketNo";
  private String ticketNo;

  /**
   * Ticket type
   */
  public enum TicketTypeEnum {
    FULL("FULL"),
    
    HALF("HALF");

    private String value;

    TicketTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TicketTypeEnum fromValue(String value) {
      for (TicketTypeEnum b : TicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TICKET_TYPE = "ticketType";
  private TicketTypeEnum ticketType;

  public SeatReservationInfo() {
  }

  public SeatReservationInfo seatId(Long seatId) {
    
    this.seatId = seatId;
    return this;
  }

   /**
   * Seat ID
   * @return seatId
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeatId() {
    return seatId;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatId(Long seatId) {
    this.seatId = seatId;
  }


  public SeatReservationInfo seatNo(String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

   /**
   * Seat number
   * @return seatNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNo(String seatNo) {
    this.seatNo = seatNo;
  }


  public SeatReservationInfo tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Table name
   * @return tableName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  public SeatReservationInfo ticketNo(String ticketNo) {
    
    this.ticketNo = ticketNo;
    return this;
  }

   /**
   * Ticket number
   * @return ticketNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketNo() {
    return ticketNo;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketNo(String ticketNo) {
    this.ticketNo = ticketNo;
  }


  public SeatReservationInfo ticketType(TicketTypeEnum ticketType) {
    
    this.ticketType = ticketType;
    return this;
  }

   /**
   * Ticket type
   * @return ticketType
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TicketTypeEnum getTicketType() {
    return ticketType;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatReservationInfo seatReservationInfo = (SeatReservationInfo) o;
    return Objects.equals(this.seatId, seatReservationInfo.seatId) &&
        Objects.equals(this.seatNo, seatReservationInfo.seatNo) &&
        Objects.equals(this.tableName, seatReservationInfo.tableName) &&
        Objects.equals(this.ticketNo, seatReservationInfo.ticketNo) &&
        Objects.equals(this.ticketType, seatReservationInfo.ticketType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seatId, seatNo, tableName, ticketNo, ticketType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatReservationInfo {\n");
    sb.append("    seatId: ").append(toIndentedString(seatId)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    ticketNo: ").append(toIndentedString(ticketNo)).append("\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

