/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Seat information
 */
@JsonPropertyOrder({
  SeatInfo.JSON_PROPERTY_ID,
  SeatInfo.JSON_PROPERTY_SEAT_NO,
  SeatInfo.JSON_PROPERTY_TABLE_ID,
  SeatInfo.JSON_PROPERTY_TABLE_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SeatInfo implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  private String seatNo;

  public static final String JSON_PROPERTY_TABLE_ID = "tableId";
  private Long tableId;

  public static final String JSON_PROPERTY_TABLE_NAME = "tableName";
  private String tableName;

  public SeatInfo() {
  }

  public SeatInfo id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Seat ID
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public SeatInfo seatNo(String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

   /**
   * Seat number
   * @return seatNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNo(String seatNo) {
    this.seatNo = seatNo;
  }


  public SeatInfo tableId(Long tableId) {
    
    this.tableId = tableId;
    return this;
  }

   /**
   * Table ID
   * @return tableId
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTableId() {
    return tableId;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableId(Long tableId) {
    this.tableId = tableId;
  }


  public SeatInfo tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Table name
   * @return tableName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatInfo seatInfo = (SeatInfo) o;
    return Objects.equals(this.id, seatInfo.id) &&
        Objects.equals(this.seatNo, seatInfo.seatNo) &&
        Objects.equals(this.tableId, seatInfo.tableId) &&
        Objects.equals(this.tableName, seatInfo.tableName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seatNo, tableId, tableName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    tableId: ").append(toIndentedString(tableId)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

