/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.amithfernando.qrseatreservation.client.model.TableDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * SeatDetail
 */
@JsonPropertyOrder({
  SeatDetail.JSON_PROPERTY_ID,
  SeatDetail.JSON_PROPERTY_SEAT_NO,
  SeatDetail.JSON_PROPERTY_SEAT_STATUS,
  SeatDetail.JSON_PROPERTY_TABLE_DETAIL,
  SeatDetail.JSON_PROPERTY_CREATED_AT,
  SeatDetail.JSON_PROPERTY_UPDATED_AT,
  SeatDetail.JSON_PROPERTY_CREATED_BY,
  SeatDetail.JSON_PROPERTY_UPDATED_BY,
  SeatDetail.JSON_PROPERTY_AVAILABLE,
  SeatDetail.JSON_PROPERTY_NO_WITH_STATUS,
  SeatDetail.JSON_PROPERTY_UNAVAILABLE,
  SeatDetail.JSON_PROPERTY_CHECKED_IN,
  SeatDetail.JSON_PROPERTY_RESERVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SeatDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  private String seatNo;

  /**
   * Gets or Sets seatStatus
   */
  public enum SeatStatusEnum {
    AVAILABLE("AVAILABLE"),
    
    RESERVED("RESERVED"),
    
    UNAVAILABLE("UNAVAILABLE"),
    
    CHECKED_IN("CHECKED_IN");

    private String value;

    SeatStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SeatStatusEnum fromValue(String value) {
      for (SeatStatusEnum b : SeatStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SEAT_STATUS = "seatStatus";
  private SeatStatusEnum seatStatus;

  public static final String JSON_PROPERTY_TABLE_DETAIL = "tableDetail";
  private TableDetail tableDetail;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  private String updatedBy;

  public static final String JSON_PROPERTY_AVAILABLE = "available";
  private Boolean available;

  public static final String JSON_PROPERTY_NO_WITH_STATUS = "noWithStatus";
  private String noWithStatus;

  public static final String JSON_PROPERTY_UNAVAILABLE = "unavailable";
  private Boolean unavailable;

  public static final String JSON_PROPERTY_CHECKED_IN = "checkedIn";
  private Boolean checkedIn;

  public static final String JSON_PROPERTY_RESERVED = "reserved";
  private Boolean reserved;

  public SeatDetail() {
  }

  public SeatDetail id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public SeatDetail seatNo(String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

   /**
   * Get seatNo
   * @return seatNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNo(String seatNo) {
    this.seatNo = seatNo;
  }


  public SeatDetail seatStatus(SeatStatusEnum seatStatus) {
    
    this.seatStatus = seatStatus;
    return this;
  }

   /**
   * Get seatStatus
   * @return seatStatus
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SeatStatusEnum getSeatStatus() {
    return seatStatus;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatStatus(SeatStatusEnum seatStatus) {
    this.seatStatus = seatStatus;
  }


  public SeatDetail tableDetail(TableDetail tableDetail) {
    
    this.tableDetail = tableDetail;
    return this;
  }

   /**
   * Get tableDetail
   * @return tableDetail
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_TABLE_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TableDetail getTableDetail() {
    return tableDetail;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableDetail(TableDetail tableDetail) {
    this.tableDetail = tableDetail;
  }


  public SeatDetail createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public SeatDetail updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SeatDetail createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public SeatDetail updatedBy(String updatedBy) {
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public SeatDetail available(Boolean available) {
    
    this.available = available;
    return this;
  }

   /**
   * Get available
   * @return available
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAvailable() {
    return available;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailable(Boolean available) {
    this.available = available;
  }


  public SeatDetail noWithStatus(String noWithStatus) {
    
    this.noWithStatus = noWithStatus;
    return this;
  }

   /**
   * Get noWithStatus
   * @return noWithStatus
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NO_WITH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNoWithStatus() {
    return noWithStatus;
  }


  @JsonProperty(JSON_PROPERTY_NO_WITH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoWithStatus(String noWithStatus) {
    this.noWithStatus = noWithStatus;
  }


  public SeatDetail unavailable(Boolean unavailable) {
    
    this.unavailable = unavailable;
    return this;
  }

   /**
   * Get unavailable
   * @return unavailable
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUnavailable() {
    return unavailable;
  }


  @JsonProperty(JSON_PROPERTY_UNAVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnavailable(Boolean unavailable) {
    this.unavailable = unavailable;
  }


  public SeatDetail checkedIn(Boolean checkedIn) {
    
    this.checkedIn = checkedIn;
    return this;
  }

   /**
   * Get checkedIn
   * @return checkedIn
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckedIn() {
    return checkedIn;
  }


  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckedIn(Boolean checkedIn) {
    this.checkedIn = checkedIn;
  }


  public SeatDetail reserved(Boolean reserved) {
    
    this.reserved = reserved;
    return this;
  }

   /**
   * Get reserved
   * @return reserved
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESERVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getReserved() {
    return reserved;
  }


  @JsonProperty(JSON_PROPERTY_RESERVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReserved(Boolean reserved) {
    this.reserved = reserved;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatDetail seatDetail = (SeatDetail) o;
    return Objects.equals(this.id, seatDetail.id) &&
        Objects.equals(this.seatNo, seatDetail.seatNo) &&
        Objects.equals(this.seatStatus, seatDetail.seatStatus) &&
        Objects.equals(this.tableDetail, seatDetail.tableDetail) &&
        Objects.equals(this.createdAt, seatDetail.createdAt) &&
        Objects.equals(this.updatedAt, seatDetail.updatedAt) &&
        Objects.equals(this.createdBy, seatDetail.createdBy) &&
        Objects.equals(this.updatedBy, seatDetail.updatedBy) &&
        Objects.equals(this.available, seatDetail.available) &&
        Objects.equals(this.noWithStatus, seatDetail.noWithStatus) &&
        Objects.equals(this.unavailable, seatDetail.unavailable) &&
        Objects.equals(this.checkedIn, seatDetail.checkedIn) &&
        Objects.equals(this.reserved, seatDetail.reserved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seatNo, seatStatus, tableDetail, createdAt, updatedAt, createdBy, updatedBy, available, noWithStatus, unavailable, checkedIn, reserved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    seatStatus: ").append(toIndentedString(seatStatus)).append("\n");
    sb.append("    tableDetail: ").append(toIndentedString(tableDetail)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    noWithStatus: ").append(toIndentedString(noWithStatus)).append("\n");
    sb.append("    unavailable: ").append(toIndentedString(unavailable)).append("\n");
    sb.append("    checkedIn: ").append(toIndentedString(checkedIn)).append("\n");
    sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

