/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Individual seat reservation with ticket type
 */
@JsonPropertyOrder({
  SeatReservationItem.JSON_PROPERTY_SEAT_ID,
  SeatReservationItem.JSON_PROPERTY_TICKET_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SeatReservationItem implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SEAT_ID = "seatId";
  private Long seatId;

  /**
   * Type of ticket (FULL or HALF)
   */
  public enum TicketTypeEnum {
    FULL("FULL"),
    
    HALF("HALF");

    private String value;

    TicketTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TicketTypeEnum fromValue(String value) {
      for (TicketTypeEnum b : TicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TICKET_TYPE = "ticketType";
  private TicketTypeEnum ticketType;

  public SeatReservationItem() {
  }

  public SeatReservationItem seatId(Long seatId) {
    
    this.seatId = seatId;
    return this;
  }

   /**
   * ID of the seat to reserve
   * @return seatId
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSeatId() {
    return seatId;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatId(Long seatId) {
    this.seatId = seatId;
  }


  public SeatReservationItem ticketType(TicketTypeEnum ticketType) {
    
    this.ticketType = ticketType;
    return this;
  }

   /**
   * Type of ticket (FULL or HALF)
   * @return ticketType
  **/
  @jakarta.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TicketTypeEnum getTicketType() {
    return ticketType;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTicketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatReservationItem seatReservationItem = (SeatReservationItem) o;
    return Objects.equals(this.seatId, seatReservationItem.seatId) &&
        Objects.equals(this.ticketType, seatReservationItem.ticketType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seatId, ticketType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatReservationItem {\n");
    sb.append("    seatId: ").append(toIndentedString(seatId)).append("\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

