/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Setting
 */
@JsonPropertyOrder({
  Setting.JSON_PROPERTY_ID,
  Setting.JSON_PROPERTY_EVENT_NAME,
  Setting.JSON_PROPERTY_VENUE,
  Setting.JSON_PROPERTY_TABLE_SIZE,
  Setting.JSON_PROPERTY_SEAT_SIZE,
  Setting.JSON_PROPERTY_NO_OF_COLUMNS,
  Setting.JSON_PROPERTY_BASE_IMAGE,
  Setting.JSON_PROPERTY_FONT_SIZE,
  Setting.JSON_PROPERTY_QR_X,
  Setting.JSON_PROPERTY_QR_Y,
  Setting.JSON_PROPERTY_TEXT_X,
  Setting.JSON_PROPERTY_TEXT_Y,
  Setting.JSON_PROPERTY_TICKET_PREFIX,
  Setting.JSON_PROPERTY_NO_OF_DIGITS,
  Setting.JSON_PROPERTY_MAX_NO_OF_TICKETS,
  Setting.JSON_PROPERTY_CREATED_AT,
  Setting.JSON_PROPERTY_UPDATED_AT,
  Setting.JSON_PROPERTY_CREATED_BY,
  Setting.JSON_PROPERTY_UPDATED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Setting implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_EVENT_NAME = "eventName";
  private String eventName;

  public static final String JSON_PROPERTY_VENUE = "venue";
  private String venue;

  public static final String JSON_PROPERTY_TABLE_SIZE = "tableSize";
  private Integer tableSize;

  public static final String JSON_PROPERTY_SEAT_SIZE = "seatSize";
  private Integer seatSize;

  public static final String JSON_PROPERTY_NO_OF_COLUMNS = "noOfColumns";
  private Integer noOfColumns;

  public static final String JSON_PROPERTY_BASE_IMAGE = "baseImage";
  private byte[] baseImage;

  public static final String JSON_PROPERTY_FONT_SIZE = "fontSize";
  private Integer fontSize;

  public static final String JSON_PROPERTY_QR_X = "qrX";
  private Integer qrX;

  public static final String JSON_PROPERTY_QR_Y = "qrY";
  private Integer qrY;

  public static final String JSON_PROPERTY_TEXT_X = "textX";
  private Integer textX;

  public static final String JSON_PROPERTY_TEXT_Y = "textY";
  private Integer textY;

  public static final String JSON_PROPERTY_TICKET_PREFIX = "ticketPrefix";
  private String ticketPrefix;

  public static final String JSON_PROPERTY_NO_OF_DIGITS = "noOfDigits";
  private Integer noOfDigits;

  public static final String JSON_PROPERTY_MAX_NO_OF_TICKETS = "maxNoOfTickets";
  private Integer maxNoOfTickets;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  private String updatedBy;

  public Setting() {
  }

  public Setting id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public Setting eventName(String eventName) {
    
    this.eventName = eventName;
    return this;
  }

   /**
   * Get eventName
   * @return eventName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventName() {
    return eventName;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventName(String eventName) {
    this.eventName = eventName;
  }


  public Setting venue(String venue) {
    
    this.venue = venue;
    return this;
  }

   /**
   * Get venue
   * @return venue
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVenue() {
    return venue;
  }


  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVenue(String venue) {
    this.venue = venue;
  }


  public Setting tableSize(Integer tableSize) {
    
    this.tableSize = tableSize;
    return this;
  }

   /**
   * Get tableSize
   * @return tableSize
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTableSize() {
    return tableSize;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableSize(Integer tableSize) {
    this.tableSize = tableSize;
  }


  public Setting seatSize(Integer seatSize) {
    
    this.seatSize = seatSize;
    return this;
  }

   /**
   * Get seatSize
   * @return seatSize
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_SEAT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeatSize() {
    return seatSize;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatSize(Integer seatSize) {
    this.seatSize = seatSize;
  }


  public Setting noOfColumns(Integer noOfColumns) {
    
    this.noOfColumns = noOfColumns;
    return this;
  }

   /**
   * Get noOfColumns
   * @return noOfColumns
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NO_OF_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfColumns() {
    return noOfColumns;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfColumns(Integer noOfColumns) {
    this.noOfColumns = noOfColumns;
  }


  public Setting baseImage(byte[] baseImage) {
    
    this.baseImage = baseImage;
    return this;
  }

   /**
   * Get baseImage
   * @return baseImage
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BASE_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public byte[] getBaseImage() {
    return baseImage;
  }


  @JsonProperty(JSON_PROPERTY_BASE_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseImage(byte[] baseImage) {
    this.baseImage = baseImage;
  }


  public Setting fontSize(Integer fontSize) {
    
    this.fontSize = fontSize;
    return this;
  }

   /**
   * Get fontSize
   * @return fontSize
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFontSize() {
    return fontSize;
  }


  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontSize(Integer fontSize) {
    this.fontSize = fontSize;
  }


  public Setting qrX(Integer qrX) {
    
    this.qrX = qrX;
    return this;
  }

   /**
   * Get qrX
   * @return qrX
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_QR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQrX() {
    return qrX;
  }


  @JsonProperty(JSON_PROPERTY_QR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrX(Integer qrX) {
    this.qrX = qrX;
  }


  public Setting qrY(Integer qrY) {
    
    this.qrY = qrY;
    return this;
  }

   /**
   * Get qrY
   * @return qrY
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_QR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQrY() {
    return qrY;
  }


  @JsonProperty(JSON_PROPERTY_QR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrY(Integer qrY) {
    this.qrY = qrY;
  }


  public Setting textX(Integer textX) {
    
    this.textX = textX;
    return this;
  }

   /**
   * Get textX
   * @return textX
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TEXT_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTextX() {
    return textX;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextX(Integer textX) {
    this.textX = textX;
  }


  public Setting textY(Integer textY) {
    
    this.textY = textY;
    return this;
  }

   /**
   * Get textY
   * @return textY
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TEXT_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTextY() {
    return textY;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextY(Integer textY) {
    this.textY = textY;
  }


  public Setting ticketPrefix(String ticketPrefix) {
    
    this.ticketPrefix = ticketPrefix;
    return this;
  }

   /**
   * Get ticketPrefix
   * @return ticketPrefix
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketPrefix() {
    return ticketPrefix;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketPrefix(String ticketPrefix) {
    this.ticketPrefix = ticketPrefix;
  }


  public Setting noOfDigits(Integer noOfDigits) {
    
    this.noOfDigits = noOfDigits;
    return this;
  }

   /**
   * Get noOfDigits
   * @return noOfDigits
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NO_OF_DIGITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfDigits() {
    return noOfDigits;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_DIGITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfDigits(Integer noOfDigits) {
    this.noOfDigits = noOfDigits;
  }


  public Setting maxNoOfTickets(Integer maxNoOfTickets) {
    
    this.maxNoOfTickets = maxNoOfTickets;
    return this;
  }

   /**
   * Get maxNoOfTickets
   * @return maxNoOfTickets
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MAX_NO_OF_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxNoOfTickets() {
    return maxNoOfTickets;
  }


  @JsonProperty(JSON_PROPERTY_MAX_NO_OF_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxNoOfTickets(Integer maxNoOfTickets) {
    this.maxNoOfTickets = maxNoOfTickets;
  }


  public Setting createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Setting updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Setting createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public Setting updatedBy(String updatedBy) {
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Setting setting = (Setting) o;
    return Objects.equals(this.id, setting.id) &&
        Objects.equals(this.eventName, setting.eventName) &&
        Objects.equals(this.venue, setting.venue) &&
        Objects.equals(this.tableSize, setting.tableSize) &&
        Objects.equals(this.seatSize, setting.seatSize) &&
        Objects.equals(this.noOfColumns, setting.noOfColumns) &&
        Arrays.equals(this.baseImage, setting.baseImage) &&
        Objects.equals(this.fontSize, setting.fontSize) &&
        Objects.equals(this.qrX, setting.qrX) &&
        Objects.equals(this.qrY, setting.qrY) &&
        Objects.equals(this.textX, setting.textX) &&
        Objects.equals(this.textY, setting.textY) &&
        Objects.equals(this.ticketPrefix, setting.ticketPrefix) &&
        Objects.equals(this.noOfDigits, setting.noOfDigits) &&
        Objects.equals(this.maxNoOfTickets, setting.maxNoOfTickets) &&
        Objects.equals(this.createdAt, setting.createdAt) &&
        Objects.equals(this.updatedAt, setting.updatedAt) &&
        Objects.equals(this.createdBy, setting.createdBy) &&
        Objects.equals(this.updatedBy, setting.updatedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, eventName, venue, tableSize, seatSize, noOfColumns, Arrays.hashCode(baseImage), fontSize, qrX, qrY, textX, textY, ticketPrefix, noOfDigits, maxNoOfTickets, createdAt, updatedAt, createdBy, updatedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Setting {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    venue: ").append(toIndentedString(venue)).append("\n");
    sb.append("    tableSize: ").append(toIndentedString(tableSize)).append("\n");
    sb.append("    seatSize: ").append(toIndentedString(seatSize)).append("\n");
    sb.append("    noOfColumns: ").append(toIndentedString(noOfColumns)).append("\n");
    sb.append("    baseImage: ").append(toIndentedString(baseImage)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    qrX: ").append(toIndentedString(qrX)).append("\n");
    sb.append("    qrY: ").append(toIndentedString(qrY)).append("\n");
    sb.append("    textX: ").append(toIndentedString(textX)).append("\n");
    sb.append("    textY: ").append(toIndentedString(textY)).append("\n");
    sb.append("    ticketPrefix: ").append(toIndentedString(ticketPrefix)).append("\n");
    sb.append("    noOfDigits: ").append(toIndentedString(noOfDigits)).append("\n");
    sb.append("    maxNoOfTickets: ").append(toIndentedString(maxNoOfTickets)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

