/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TableDetailSummary
 */
@JsonPropertyOrder({
  TableDetailSummary.JSON_PROPERTY_TOTAL_NO_OF_TABLES,
  TableDetailSummary.JSON_PROPERTY_TOTAL_NO_OF_TOTAL_SEATS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TableDetailSummary implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL_NO_OF_TABLES = "totalNoOfTables";
  private Integer totalNoOfTables;

  public static final String JSON_PROPERTY_TOTAL_NO_OF_TOTAL_SEATS = "totalNoOfTotalSeats";
  private Integer totalNoOfTotalSeats;

  public TableDetailSummary() {
  }

  public TableDetailSummary totalNoOfTables(Integer totalNoOfTables) {
    
    this.totalNoOfTables = totalNoOfTables;
    return this;
  }

   /**
   * Get totalNoOfTables
   * @return totalNoOfTables
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_NO_OF_TABLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalNoOfTables() {
    return totalNoOfTables;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_NO_OF_TABLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalNoOfTables(Integer totalNoOfTables) {
    this.totalNoOfTables = totalNoOfTables;
  }


  public TableDetailSummary totalNoOfTotalSeats(Integer totalNoOfTotalSeats) {
    
    this.totalNoOfTotalSeats = totalNoOfTotalSeats;
    return this;
  }

   /**
   * Get totalNoOfTotalSeats
   * @return totalNoOfTotalSeats
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL_NO_OF_TOTAL_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalNoOfTotalSeats() {
    return totalNoOfTotalSeats;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_NO_OF_TOTAL_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalNoOfTotalSeats(Integer totalNoOfTotalSeats) {
    this.totalNoOfTotalSeats = totalNoOfTotalSeats;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableDetailSummary tableDetailSummary = (TableDetailSummary) o;
    return Objects.equals(this.totalNoOfTables, tableDetailSummary.totalNoOfTables) &&
        Objects.equals(this.totalNoOfTotalSeats, tableDetailSummary.totalNoOfTotalSeats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalNoOfTables, totalNoOfTotalSeats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableDetailSummary {\n");
    sb.append("    totalNoOfTables: ").append(toIndentedString(totalNoOfTables)).append("\n");
    sb.append("    totalNoOfTotalSeats: ").append(toIndentedString(totalNoOfTotalSeats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

