/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.amithfernando.qrseatreservation.client.model.SeatDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * TableDetail
 */
@JsonPropertyOrder({
  TableDetail.JSON_PROPERTY_ID,
  TableDetail.JSON_PROPERTY_TABLE_NAME,
  TableDetail.JSON_PROPERTY_DESCRIPTION,
  TableDetail.JSON_PROPERTY_NO_OF_SEATS,
  TableDetail.JSON_PROPERTY_SEAT_DETAILS,
  TableDetail.JSON_PROPERTY_CREATED_AT,
  TableDetail.JSON_PROPERTY_UPDATED_AT,
  TableDetail.JSON_PROPERTY_CREATED_BY,
  TableDetail.JSON_PROPERTY_UPDATED_BY,
  TableDetail.JSON_PROPERTY_TABLE_NO_WITH_STATUS,
  TableDetail.JSON_PROPERTY_AVAILABLE_SEATS,
  TableDetail.JSON_PROPERTY_UNAVAILABLE_SEATS,
  TableDetail.JSON_PROPERTY_RESERVED_SEATS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TableDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_TABLE_NAME = "tableName";
  private String tableName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_NO_OF_SEATS = "noOfSeats";
  private Integer noOfSeats;

  public static final String JSON_PROPERTY_SEAT_DETAILS = "seatDetails";
  private List<@Valid SeatDetail> seatDetails;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "createdBy";
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updatedBy";
  private String updatedBy;

  public static final String JSON_PROPERTY_TABLE_NO_WITH_STATUS = "tableNoWithStatus";
  private String tableNoWithStatus;

  public static final String JSON_PROPERTY_AVAILABLE_SEATS = "availableSeats";
  private Long availableSeats;

  public static final String JSON_PROPERTY_UNAVAILABLE_SEATS = "unavailableSeats";
  private Long unavailableSeats;

  public static final String JSON_PROPERTY_RESERVED_SEATS = "reservedSeats";
  private Long reservedSeats;

  public TableDetail() {
  }

  public TableDetail id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TableDetail tableName(String tableName) {
    
    this.tableName = tableName;
    return this;
  }

   /**
   * Get tableName
   * @return tableName
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableName() {
    return tableName;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  public TableDetail description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public TableDetail noOfSeats(Integer noOfSeats) {
    
    this.noOfSeats = noOfSeats;
    return this;
  }

   /**
   * Get noOfSeats
   * @return noOfSeats
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_NO_OF_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfSeats() {
    return noOfSeats;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfSeats(Integer noOfSeats) {
    this.noOfSeats = noOfSeats;
  }


  public TableDetail seatDetails(List<@Valid SeatDetail> seatDetails) {
    
    this.seatDetails = seatDetails;
    return this;
  }

  public TableDetail addSeatDetailsItem(SeatDetail seatDetailsItem) {
    if (this.seatDetails == null) {
      this.seatDetails = new ArrayList<>();
    }
    this.seatDetails.add(seatDetailsItem);
    return this;
  }

   /**
   * Get seatDetails
   * @return seatDetails
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<@Valid SeatDetail> getSeatDetails() {
    return seatDetails;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatDetails(List<@Valid SeatDetail> seatDetails) {
    this.seatDetails = seatDetails;
  }


  public TableDetail createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TableDetail updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TableDetail createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public TableDetail updatedBy(String updatedBy) {
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public TableDetail tableNoWithStatus(String tableNoWithStatus) {
    
    this.tableNoWithStatus = tableNoWithStatus;
    return this;
  }

   /**
   * Get tableNoWithStatus
   * @return tableNoWithStatus
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TABLE_NO_WITH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTableNoWithStatus() {
    return tableNoWithStatus;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_NO_WITH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableNoWithStatus(String tableNoWithStatus) {
    this.tableNoWithStatus = tableNoWithStatus;
  }


  public TableDetail availableSeats(Long availableSeats) {
    
    this.availableSeats = availableSeats;
    return this;
  }

   /**
   * Get availableSeats
   * @return availableSeats
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAvailableSeats() {
    return availableSeats;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableSeats(Long availableSeats) {
    this.availableSeats = availableSeats;
  }


  public TableDetail unavailableSeats(Long unavailableSeats) {
    
    this.unavailableSeats = unavailableSeats;
    return this;
  }

   /**
   * Get unavailableSeats
   * @return unavailableSeats
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_UNAVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUnavailableSeats() {
    return unavailableSeats;
  }


  @JsonProperty(JSON_PROPERTY_UNAVAILABLE_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnavailableSeats(Long unavailableSeats) {
    this.unavailableSeats = unavailableSeats;
  }


  public TableDetail reservedSeats(Long reservedSeats) {
    
    this.reservedSeats = reservedSeats;
    return this;
  }

   /**
   * Get reservedSeats
   * @return reservedSeats
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESERVED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getReservedSeats() {
    return reservedSeats;
  }


  @JsonProperty(JSON_PROPERTY_RESERVED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReservedSeats(Long reservedSeats) {
    this.reservedSeats = reservedSeats;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TableDetail tableDetail = (TableDetail) o;
    return Objects.equals(this.id, tableDetail.id) &&
        Objects.equals(this.tableName, tableDetail.tableName) &&
        Objects.equals(this.description, tableDetail.description) &&
        Objects.equals(this.noOfSeats, tableDetail.noOfSeats) &&
        Objects.equals(this.seatDetails, tableDetail.seatDetails) &&
        Objects.equals(this.createdAt, tableDetail.createdAt) &&
        Objects.equals(this.updatedAt, tableDetail.updatedAt) &&
        Objects.equals(this.createdBy, tableDetail.createdBy) &&
        Objects.equals(this.updatedBy, tableDetail.updatedBy) &&
        Objects.equals(this.tableNoWithStatus, tableDetail.tableNoWithStatus) &&
        Objects.equals(this.availableSeats, tableDetail.availableSeats) &&
        Objects.equals(this.unavailableSeats, tableDetail.unavailableSeats) &&
        Objects.equals(this.reservedSeats, tableDetail.reservedSeats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tableName, description, noOfSeats, seatDetails, createdAt, updatedAt, createdBy, updatedBy, tableNoWithStatus, availableSeats, unavailableSeats, reservedSeats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TableDetail {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    noOfSeats: ").append(toIndentedString(noOfSeats)).append("\n");
    sb.append("    seatDetails: ").append(toIndentedString(seatDetails)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    tableNoWithStatus: ").append(toIndentedString(tableNoWithStatus)).append("\n");
    sb.append("    availableSeats: ").append(toIndentedString(availableSeats)).append("\n");
    sb.append("    unavailableSeats: ").append(toIndentedString(unavailableSeats)).append("\n");
    sb.append("    reservedSeats: ").append(toIndentedString(reservedSeats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

