/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.amithfernando.qrseatreservation.client.model.SeatInfo;
import com.amithfernando.qrseatreservation.client.model.SellerInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Detailed information about a ticket
 */
@JsonPropertyOrder({
  TicketDetailsResponse.JSON_PROPERTY_TICKET_NO,
  TicketDetailsResponse.JSON_PROPERTY_TICKET_TYPE,
  TicketDetailsResponse.JSON_PROPERTY_RESERVATION_STATUS,
  TicketDetailsResponse.JSON_PROPERTY_CAN_CHECK_IN,
  TicketDetailsResponse.JSON_PROPERTY_CHECK_IN_MESSAGE,
  TicketDetailsResponse.JSON_PROPERTY_SELLER,
  TicketDetailsResponse.JSON_PROPERTY_SEAT,
  TicketDetailsResponse.JSON_PROPERTY_RESERVATION_REFERENCE_NO,
  TicketDetailsResponse.JSON_PROPERTY_RESERVATION_CREATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TicketDetailsResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TICKET_NO = "ticketNo";
  private String ticketNo;

  /**
   * Ticket type (FULL or HALF)
   */
  public enum TicketTypeEnum {
    FULL("FULL"),
    
    HALF("HALF");

    private String value;

    TicketTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TicketTypeEnum fromValue(String value) {
      for (TicketTypeEnum b : TicketTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TICKET_TYPE = "ticketType";
  private TicketTypeEnum ticketType;

  /**
   * Current reservation status
   */
  public enum ReservationStatusEnum {
    PAYMENT_PENDING("PAYMENT_PENDING"),
    
    PAID("PAID"),
    
    CHECKED_IN("CHECKED_IN");

    private String value;

    ReservationStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReservationStatusEnum fromValue(String value) {
      for (ReservationStatusEnum b : ReservationStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESERVATION_STATUS = "reservationStatus";
  private ReservationStatusEnum reservationStatus;

  public static final String JSON_PROPERTY_CAN_CHECK_IN = "canCheckIn";
  private Boolean canCheckIn;

  public static final String JSON_PROPERTY_CHECK_IN_MESSAGE = "checkInMessage";
  private String checkInMessage;

  public static final String JSON_PROPERTY_SELLER = "seller";
  private SellerInfo seller;

  public static final String JSON_PROPERTY_SEAT = "seat";
  private SeatInfo seat;

  public static final String JSON_PROPERTY_RESERVATION_REFERENCE_NO = "reservationReferenceNo";
  private String reservationReferenceNo;

  public static final String JSON_PROPERTY_RESERVATION_CREATED_AT = "reservationCreatedAt";
  private OffsetDateTime reservationCreatedAt;

  public TicketDetailsResponse() {
  }

  public TicketDetailsResponse ticketNo(String ticketNo) {
    
    this.ticketNo = ticketNo;
    return this;
  }

   /**
   * Ticket number
   * @return ticketNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketNo() {
    return ticketNo;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketNo(String ticketNo) {
    this.ticketNo = ticketNo;
  }


  public TicketDetailsResponse ticketType(TicketTypeEnum ticketType) {
    
    this.ticketType = ticketType;
    return this;
  }

   /**
   * Ticket type (FULL or HALF)
   * @return ticketType
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TicketTypeEnum getTicketType() {
    return ticketType;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketType(TicketTypeEnum ticketType) {
    this.ticketType = ticketType;
  }


  public TicketDetailsResponse reservationStatus(ReservationStatusEnum reservationStatus) {
    
    this.reservationStatus = reservationStatus;
    return this;
  }

   /**
   * Current reservation status
   * @return reservationStatus
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESERVATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReservationStatusEnum getReservationStatus() {
    return reservationStatus;
  }


  @JsonProperty(JSON_PROPERTY_RESERVATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReservationStatus(ReservationStatusEnum reservationStatus) {
    this.reservationStatus = reservationStatus;
  }


  public TicketDetailsResponse canCheckIn(Boolean canCheckIn) {
    
    this.canCheckIn = canCheckIn;
    return this;
  }

   /**
   * Whether ticket can be checked in
   * @return canCheckIn
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CAN_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanCheckIn() {
    return canCheckIn;
  }


  @JsonProperty(JSON_PROPERTY_CAN_CHECK_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanCheckIn(Boolean canCheckIn) {
    this.canCheckIn = canCheckIn;
  }


  public TicketDetailsResponse checkInMessage(String checkInMessage) {
    
    this.checkInMessage = checkInMessage;
    return this;
  }

   /**
   * Reason if check-in is not allowed
   * @return checkInMessage
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_CHECK_IN_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckInMessage() {
    return checkInMessage;
  }


  @JsonProperty(JSON_PROPERTY_CHECK_IN_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckInMessage(String checkInMessage) {
    this.checkInMessage = checkInMessage;
  }


  public TicketDetailsResponse seller(SellerInfo seller) {
    
    this.seller = seller;
    return this;
  }

   /**
   * Seller information
   * @return seller
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SellerInfo getSeller() {
    return seller;
  }


  @JsonProperty(JSON_PROPERTY_SELLER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeller(SellerInfo seller) {
    this.seller = seller;
  }


  public TicketDetailsResponse seat(SeatInfo seat) {
    
    this.seat = seat;
    return this;
  }

   /**
   * Seat information
   * @return seat
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_SEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SeatInfo getSeat() {
    return seat;
  }


  @JsonProperty(JSON_PROPERTY_SEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeat(SeatInfo seat) {
    this.seat = seat;
  }


  public TicketDetailsResponse reservationReferenceNo(String reservationReferenceNo) {
    
    this.reservationReferenceNo = reservationReferenceNo;
    return this;
  }

   /**
   * Reservation reference number
   * @return reservationReferenceNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_RESERVATION_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReservationReferenceNo() {
    return reservationReferenceNo;
  }


  @JsonProperty(JSON_PROPERTY_RESERVATION_REFERENCE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReservationReferenceNo(String reservationReferenceNo) {
    this.reservationReferenceNo = reservationReferenceNo;
  }


  public TicketDetailsResponse reservationCreatedAt(OffsetDateTime reservationCreatedAt) {
    
    this.reservationCreatedAt = reservationCreatedAt;
    return this;
  }

   /**
   * Reservation creation time
   * @return reservationCreatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_RESERVATION_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getReservationCreatedAt() {
    return reservationCreatedAt;
  }


  @JsonProperty(JSON_PROPERTY_RESERVATION_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReservationCreatedAt(OffsetDateTime reservationCreatedAt) {
    this.reservationCreatedAt = reservationCreatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketDetailsResponse ticketDetailsResponse = (TicketDetailsResponse) o;
    return Objects.equals(this.ticketNo, ticketDetailsResponse.ticketNo) &&
        Objects.equals(this.ticketType, ticketDetailsResponse.ticketType) &&
        Objects.equals(this.reservationStatus, ticketDetailsResponse.reservationStatus) &&
        Objects.equals(this.canCheckIn, ticketDetailsResponse.canCheckIn) &&
        Objects.equals(this.checkInMessage, ticketDetailsResponse.checkInMessage) &&
        Objects.equals(this.seller, ticketDetailsResponse.seller) &&
        Objects.equals(this.seat, ticketDetailsResponse.seat) &&
        Objects.equals(this.reservationReferenceNo, ticketDetailsResponse.reservationReferenceNo) &&
        Objects.equals(this.reservationCreatedAt, ticketDetailsResponse.reservationCreatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketNo, ticketType, reservationStatus, canCheckIn, checkInMessage, seller, seat, reservationReferenceNo, reservationCreatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketDetailsResponse {\n");
    sb.append("    ticketNo: ").append(toIndentedString(ticketNo)).append("\n");
    sb.append("    ticketType: ").append(toIndentedString(ticketType)).append("\n");
    sb.append("    reservationStatus: ").append(toIndentedString(reservationStatus)).append("\n");
    sb.append("    canCheckIn: ").append(toIndentedString(canCheckIn)).append("\n");
    sb.append("    checkInMessage: ").append(toIndentedString(checkInMessage)).append("\n");
    sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
    sb.append("    seat: ").append(toIndentedString(seat)).append("\n");
    sb.append("    reservationReferenceNo: ").append(toIndentedString(reservationReferenceNo)).append("\n");
    sb.append("    reservationCreatedAt: ").append(toIndentedString(reservationCreatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

