/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Ticket statistics
 */
@JsonPropertyOrder({
  TicketStatsResponse.JSON_PROPERTY_TOTAL,
  TicketStatsResponse.JSON_PROPERTY_AVAILABLE,
  TicketStatsResponse.JSON_PROPERTY_USED,
  TicketStatsResponse.JSON_PROPERTY_USAGE_PERCENTAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TicketStatsResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TOTAL = "total";
  private Long total;

  public static final String JSON_PROPERTY_AVAILABLE = "available";
  private Long available;

  public static final String JSON_PROPERTY_USED = "used";
  private Long used;

  public static final String JSON_PROPERTY_USAGE_PERCENTAGE = "usagePercentage";
  private Double usagePercentage;

  public TicketStatsResponse() {
  }

  public TicketStatsResponse total(Long total) {
    
    this.total = total;
    return this;
  }

   /**
   * Total number of tickets
   * @return total
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotal() {
    return total;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(Long total) {
    this.total = total;
  }


  public TicketStatsResponse available(Long available) {
    
    this.available = available;
    return this;
  }

   /**
   * Number of available tickets
   * @return available
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAvailable() {
    return available;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailable(Long available) {
    this.available = available;
  }


  public TicketStatsResponse used(Long used) {
    
    this.used = used;
    return this;
  }

   /**
   * Number of used tickets
   * @return used
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_USED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUsed() {
    return used;
  }


  @JsonProperty(JSON_PROPERTY_USED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsed(Long used) {
    this.used = used;
  }


  public TicketStatsResponse usagePercentage(Double usagePercentage) {
    
    this.usagePercentage = usagePercentage;
    return this;
  }

   /**
   * Percentage of tickets used
   * @return usagePercentage
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_USAGE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getUsagePercentage() {
    return usagePercentage;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsagePercentage(Double usagePercentage) {
    this.usagePercentage = usagePercentage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketStatsResponse ticketStatsResponse = (TicketStatsResponse) o;
    return Objects.equals(this.total, ticketStatsResponse.total) &&
        Objects.equals(this.available, ticketStatsResponse.available) &&
        Objects.equals(this.used, ticketStatsResponse.used) &&
        Objects.equals(this.usagePercentage, ticketStatsResponse.usagePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, available, used, usagePercentage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketStatsResponse {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    usagePercentage: ").append(toIndentedString(usagePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

