/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import org.hibernate.validator.constraints.*;

/**
 * Ticket information response
 */
@JsonPropertyOrder({
  TicketResponse.JSON_PROPERTY_ID,
  TicketResponse.JSON_PROPERTY_TICKET_NO,
  TicketResponse.JSON_PROPERTY_STATUS,
  TicketResponse.JSON_PROPERTY_HAS_IMAGE,
  TicketResponse.JSON_PROPERTY_IMAGE_SIZE_BYTES,
  TicketResponse.JSON_PROPERTY_CREATED_AT,
  TicketResponse.JSON_PROPERTY_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TicketResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_TICKET_NO = "ticketNo";
  private String ticketNo;

  /**
   * Ticket status
   */
  public enum StatusEnum {
    AVAILABLE("AVAILABLE"),
    
    USED("USED"),
    
    CANCELLED("CANCELLED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_HAS_IMAGE = "hasImage";
  private Boolean hasImage;

  public static final String JSON_PROPERTY_IMAGE_SIZE_BYTES = "imageSizeBytes";
  private Integer imageSizeBytes;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  private OffsetDateTime updatedAt;

  public TicketResponse() {
  }

  public TicketResponse id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Ticket ID
   * @return id
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public TicketResponse ticketNo(String ticketNo) {
    
    this.ticketNo = ticketNo;
    return this;
  }

   /**
   * Ticket number
   * @return ticketNo
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketNo() {
    return ticketNo;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketNo(String ticketNo) {
    this.ticketNo = ticketNo;
  }


  public TicketResponse status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Ticket status
   * @return status
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public TicketResponse hasImage(Boolean hasImage) {
    
    this.hasImage = hasImage;
    return this;
  }

   /**
   * Whether ticket has image data
   * @return hasImage
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_HAS_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasImage() {
    return hasImage;
  }


  @JsonProperty(JSON_PROPERTY_HAS_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasImage(Boolean hasImage) {
    this.hasImage = hasImage;
  }


  public TicketResponse imageSizeBytes(Integer imageSizeBytes) {
    
    this.imageSizeBytes = imageSizeBytes;
    return this;
  }

   /**
   * Image data size in bytes
   * @return imageSizeBytes
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_IMAGE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getImageSizeBytes() {
    return imageSizeBytes;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_SIZE_BYTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageSizeBytes(Integer imageSizeBytes) {
    this.imageSizeBytes = imageSizeBytes;
  }


  public TicketResponse createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation timestamp
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TicketResponse updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Last update timestamp
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketResponse ticketResponse = (TicketResponse) o;
    return Objects.equals(this.id, ticketResponse.id) &&
        Objects.equals(this.ticketNo, ticketResponse.ticketNo) &&
        Objects.equals(this.status, ticketResponse.status) &&
        Objects.equals(this.hasImage, ticketResponse.hasImage) &&
        Objects.equals(this.imageSizeBytes, ticketResponse.imageSizeBytes) &&
        Objects.equals(this.createdAt, ticketResponse.createdAt) &&
        Objects.equals(this.updatedAt, ticketResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ticketNo, status, hasImage, imageSizeBytes, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ticketNo: ").append(toIndentedString(ticketNo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hasImage: ").append(toIndentedString(hasImage)).append("\n");
    sb.append("    imageSizeBytes: ").append(toIndentedString(imageSizeBytes)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

