/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Request object for updating application settings
 */
@JsonPropertyOrder({
  UpdateSettingRequest.JSON_PROPERTY_EVENT_NAME,
  UpdateSettingRequest.JSON_PROPERTY_VENUE,
  UpdateSettingRequest.JSON_PROPERTY_TABLE_SIZE,
  UpdateSettingRequest.JSON_PROPERTY_SEAT_SIZE,
  UpdateSettingRequest.JSON_PROPERTY_NO_OF_COLUMNS,
  UpdateSettingRequest.JSON_PROPERTY_FONT_SIZE,
  UpdateSettingRequest.JSON_PROPERTY_QR_X,
  UpdateSettingRequest.JSON_PROPERTY_QR_Y,
  UpdateSettingRequest.JSON_PROPERTY_TEXT_X,
  UpdateSettingRequest.JSON_PROPERTY_TEXT_Y,
  UpdateSettingRequest.JSON_PROPERTY_TICKET_PREFIX,
  UpdateSettingRequest.JSON_PROPERTY_NO_OF_DIGITS,
  UpdateSettingRequest.JSON_PROPERTY_MAX_NO_OF_TICKETS,
  UpdateSettingRequest.JSON_PROPERTY_BASE_IMAGE_BASE64
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateSettingRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_EVENT_NAME = "eventName";
  private String eventName;

  public static final String JSON_PROPERTY_VENUE = "venue";
  private String venue;

  public static final String JSON_PROPERTY_TABLE_SIZE = "tableSize";
  private Integer tableSize;

  public static final String JSON_PROPERTY_SEAT_SIZE = "seatSize";
  private Integer seatSize;

  public static final String JSON_PROPERTY_NO_OF_COLUMNS = "noOfColumns";
  private Integer noOfColumns;

  public static final String JSON_PROPERTY_FONT_SIZE = "fontSize";
  private Integer fontSize;

  public static final String JSON_PROPERTY_QR_X = "qrX";
  private Integer qrX;

  public static final String JSON_PROPERTY_QR_Y = "qrY";
  private Integer qrY;

  public static final String JSON_PROPERTY_TEXT_X = "textX";
  private Integer textX;

  public static final String JSON_PROPERTY_TEXT_Y = "textY";
  private Integer textY;

  public static final String JSON_PROPERTY_TICKET_PREFIX = "ticketPrefix";
  private String ticketPrefix;

  public static final String JSON_PROPERTY_NO_OF_DIGITS = "noOfDigits";
  private Integer noOfDigits;

  public static final String JSON_PROPERTY_MAX_NO_OF_TICKETS = "maxNoOfTickets";
  private Integer maxNoOfTickets;

  public static final String JSON_PROPERTY_BASE_IMAGE_BASE64 = "baseImageBase64";
  private String baseImageBase64;

  public UpdateSettingRequest() {
  }

  public UpdateSettingRequest eventName(String eventName) {
    
    this.eventName = eventName;
    return this;
  }

   /**
   * Event name
   * @return eventName
  **/
  @jakarta.annotation.Nonnull
  @NotNull
 @Size(min=0,max=255)
  @JsonProperty(JSON_PROPERTY_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEventName() {
    return eventName;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventName(String eventName) {
    this.eventName = eventName;
  }


  public UpdateSettingRequest venue(String venue) {
    
    this.venue = venue;
    return this;
  }

   /**
   * Venue location
   * @return venue
  **/
  @jakarta.annotation.Nullable
 @Size(min=0,max=255)
  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVenue() {
    return venue;
  }


  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVenue(String venue) {
    this.venue = venue;
  }


  public UpdateSettingRequest tableSize(Integer tableSize) {
    
    this.tableSize = tableSize;
    return this;
  }

   /**
   * Table display size in pixels
   * minimum: 10
   * @return tableSize
  **/
  @jakarta.annotation.Nullable
 @Min(10)
  @JsonProperty(JSON_PROPERTY_TABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTableSize() {
    return tableSize;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableSize(Integer tableSize) {
    this.tableSize = tableSize;
  }


  public UpdateSettingRequest seatSize(Integer seatSize) {
    
    this.seatSize = seatSize;
    return this;
  }

   /**
   * Seat display size in pixels
   * minimum: 4
   * @return seatSize
  **/
  @jakarta.annotation.Nullable
 @Min(4)
  @JsonProperty(JSON_PROPERTY_SEAT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeatSize() {
    return seatSize;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatSize(Integer seatSize) {
    this.seatSize = seatSize;
  }


  public UpdateSettingRequest noOfColumns(Integer noOfColumns) {
    
    this.noOfColumns = noOfColumns;
    return this;
  }

   /**
   * Number of columns in seating layout
   * minimum: 1
   * @return noOfColumns
  **/
  @jakarta.annotation.Nullable
 @Min(1)
  @JsonProperty(JSON_PROPERTY_NO_OF_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfColumns() {
    return noOfColumns;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfColumns(Integer noOfColumns) {
    this.noOfColumns = noOfColumns;
  }


  public UpdateSettingRequest fontSize(Integer fontSize) {
    
    this.fontSize = fontSize;
    return this;
  }

   /**
   * Font size for ticket text
   * minimum: 6
   * @return fontSize
  **/
  @jakarta.annotation.Nullable
 @Min(6)
  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFontSize() {
    return fontSize;
  }


  @JsonProperty(JSON_PROPERTY_FONT_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontSize(Integer fontSize) {
    this.fontSize = fontSize;
  }


  public UpdateSettingRequest qrX(Integer qrX) {
    
    this.qrX = qrX;
    return this;
  }

   /**
   * QR code X position on ticket
   * minimum: 0
   * @return qrX
  **/
  @jakarta.annotation.Nullable
 @Min(0)
  @JsonProperty(JSON_PROPERTY_QR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQrX() {
    return qrX;
  }


  @JsonProperty(JSON_PROPERTY_QR_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrX(Integer qrX) {
    this.qrX = qrX;
  }


  public UpdateSettingRequest qrY(Integer qrY) {
    
    this.qrY = qrY;
    return this;
  }

   /**
   * QR code Y position on ticket
   * minimum: 0
   * @return qrY
  **/
  @jakarta.annotation.Nullable
 @Min(0)
  @JsonProperty(JSON_PROPERTY_QR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQrY() {
    return qrY;
  }


  @JsonProperty(JSON_PROPERTY_QR_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrY(Integer qrY) {
    this.qrY = qrY;
  }


  public UpdateSettingRequest textX(Integer textX) {
    
    this.textX = textX;
    return this;
  }

   /**
   * Text X position on ticket
   * minimum: 0
   * @return textX
  **/
  @jakarta.annotation.Nullable
 @Min(0)
  @JsonProperty(JSON_PROPERTY_TEXT_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTextX() {
    return textX;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_X)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextX(Integer textX) {
    this.textX = textX;
  }


  public UpdateSettingRequest textY(Integer textY) {
    
    this.textY = textY;
    return this;
  }

   /**
   * Text Y position on ticket
   * minimum: 0
   * @return textY
  **/
  @jakarta.annotation.Nullable
 @Min(0)
  @JsonProperty(JSON_PROPERTY_TEXT_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTextY() {
    return textY;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_Y)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextY(Integer textY) {
    this.textY = textY;
  }


  public UpdateSettingRequest ticketPrefix(String ticketPrefix) {
    
    this.ticketPrefix = ticketPrefix;
    return this;
  }

   /**
   * Ticket number prefix
   * @return ticketPrefix
  **/
  @jakarta.annotation.Nullable
 @Size(min=0,max=32)
  @JsonProperty(JSON_PROPERTY_TICKET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicketPrefix() {
    return ticketPrefix;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicketPrefix(String ticketPrefix) {
    this.ticketPrefix = ticketPrefix;
  }


  public UpdateSettingRequest noOfDigits(Integer noOfDigits) {
    
    this.noOfDigits = noOfDigits;
    return this;
  }

   /**
   * Number of digits in ticket number
   * minimum: 1
   * @return noOfDigits
  **/
  @jakarta.annotation.Nullable
 @Min(1)
  @JsonProperty(JSON_PROPERTY_NO_OF_DIGITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoOfDigits() {
    return noOfDigits;
  }


  @JsonProperty(JSON_PROPERTY_NO_OF_DIGITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoOfDigits(Integer noOfDigits) {
    this.noOfDigits = noOfDigits;
  }


  public UpdateSettingRequest maxNoOfTickets(Integer maxNoOfTickets) {
    
    this.maxNoOfTickets = maxNoOfTickets;
    return this;
  }

   /**
   * Maximum number of tickets to generate
   * minimum: 0
   * @return maxNoOfTickets
  **/
  @jakarta.annotation.Nullable
 @Min(0)
  @JsonProperty(JSON_PROPERTY_MAX_NO_OF_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxNoOfTickets() {
    return maxNoOfTickets;
  }


  @JsonProperty(JSON_PROPERTY_MAX_NO_OF_TICKETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxNoOfTickets(Integer maxNoOfTickets) {
    this.maxNoOfTickets = maxNoOfTickets;
  }


  public UpdateSettingRequest baseImageBase64(String baseImageBase64) {
    
    this.baseImageBase64 = baseImageBase64;
    return this;
  }

   /**
   * Base image for ticket generation (Base64 encoded)
   * @return baseImageBase64
  **/
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_BASE_IMAGE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBaseImageBase64() {
    return baseImageBase64;
  }


  @JsonProperty(JSON_PROPERTY_BASE_IMAGE_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBaseImageBase64(String baseImageBase64) {
    this.baseImageBase64 = baseImageBase64;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSettingRequest updateSettingRequest = (UpdateSettingRequest) o;
    return Objects.equals(this.eventName, updateSettingRequest.eventName) &&
        Objects.equals(this.venue, updateSettingRequest.venue) &&
        Objects.equals(this.tableSize, updateSettingRequest.tableSize) &&
        Objects.equals(this.seatSize, updateSettingRequest.seatSize) &&
        Objects.equals(this.noOfColumns, updateSettingRequest.noOfColumns) &&
        Objects.equals(this.fontSize, updateSettingRequest.fontSize) &&
        Objects.equals(this.qrX, updateSettingRequest.qrX) &&
        Objects.equals(this.qrY, updateSettingRequest.qrY) &&
        Objects.equals(this.textX, updateSettingRequest.textX) &&
        Objects.equals(this.textY, updateSettingRequest.textY) &&
        Objects.equals(this.ticketPrefix, updateSettingRequest.ticketPrefix) &&
        Objects.equals(this.noOfDigits, updateSettingRequest.noOfDigits) &&
        Objects.equals(this.maxNoOfTickets, updateSettingRequest.maxNoOfTickets) &&
        Objects.equals(this.baseImageBase64, updateSettingRequest.baseImageBase64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventName, venue, tableSize, seatSize, noOfColumns, fontSize, qrX, qrY, textX, textY, ticketPrefix, noOfDigits, maxNoOfTickets, baseImageBase64);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSettingRequest {\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    venue: ").append(toIndentedString(venue)).append("\n");
    sb.append("    tableSize: ").append(toIndentedString(tableSize)).append("\n");
    sb.append("    seatSize: ").append(toIndentedString(seatSize)).append("\n");
    sb.append("    noOfColumns: ").append(toIndentedString(noOfColumns)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    qrX: ").append(toIndentedString(qrX)).append("\n");
    sb.append("    qrY: ").append(toIndentedString(qrY)).append("\n");
    sb.append("    textX: ").append(toIndentedString(textX)).append("\n");
    sb.append("    textY: ").append(toIndentedString(textY)).append("\n");
    sb.append("    ticketPrefix: ").append(toIndentedString(ticketPrefix)).append("\n");
    sb.append("    noOfDigits: ").append(toIndentedString(noOfDigits)).append("\n");
    sb.append("    maxNoOfTickets: ").append(toIndentedString(maxNoOfTickets)).append("\n");
    sb.append("    baseImageBase64: ").append(toIndentedString(baseImageBase64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

