/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CheckInResponse
 */
public class CheckInResponseTest {
    private final CheckInResponse model = new CheckInResponse();

    /**
     * Model tests for CheckInResponse
     */
    @Test
    public void testCheckInResponse() {
        // TODO: test CheckInResponse
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'ticketNo'
     */
    @Test
    public void ticketNoTest() {
        // TODO: test ticketNo
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'seatNo'
     */
    @Test
    public void seatNoTest() {
        // TODO: test seatNo
    }

    /**
     * Test the property 'tableName'
     */
    @Test
    public void tableNameTest() {
        // TODO: test tableName
    }

    /**
     * Test the property 'sellerName'
     */
    @Test
    public void sellerNameTest() {
        // TODO: test sellerName
    }

    /**
     * Test the property 'checkedInAt'
     */
    @Test
    public void checkedInAtTest() {
        // TODO: test checkedInAt
    }

}
