/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.amithfernando.qrseatreservation.client.model.SeatReservationItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateReservationRequest
 */
public class CreateReservationRequestTest {
    private final CreateReservationRequest model = new CreateReservationRequest();

    /**
     * Model tests for CreateReservationRequest
     */
    @Test
    public void testCreateReservationRequest() {
        // TODO: test CreateReservationRequest
    }

    /**
     * Test the property 'sellerId'
     */
    @Test
    public void sellerIdTest() {
        // TODO: test sellerId
    }

    /**
     * Test the property 'seatReservations'
     */
    @Test
    public void seatReservationsTest() {
        // TODO: test seatReservations
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
