/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateTableRequest
 */
public class CreateTableRequestTest {
    private final CreateTableRequest model = new CreateTableRequest();

    /**
     * Model tests for CreateTableRequest
     */
    @Test
    public void testCreateTableRequest() {
        // TODO: test CreateTableRequest
    }

    /**
     * Test the property 'tableName'
     */
    @Test
    public void tableNameTest() {
        // TODO: test tableName
    }

    /**
     * Test the property 'noOfAvailableSeats'
     */
    @Test
    public void noOfAvailableSeatsTest() {
        // TODO: test noOfAvailableSeats
    }

    /**
     * Test the property 'noOfUnavailableSeats'
     */
    @Test
    public void noOfUnavailableSeatsTest() {
        // TODO: test noOfUnavailableSeats
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
