/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.amithfernando.qrseatreservation.client.model.SeatReservationInfo;
import com.amithfernando.qrseatreservation.client.model.SellerInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ReservationResponse
 */
public class ReservationResponseTest {
    private final ReservationResponse model = new ReservationResponse();

    /**
     * Model tests for ReservationResponse
     */
    @Test
    public void testReservationResponse() {
        // TODO: test ReservationResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'referenceNo'
     */
    @Test
    public void referenceNoTest() {
        // TODO: test referenceNo
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'seatReservations'
     */
    @Test
    public void seatReservationsTest() {
        // TODO: test seatReservations
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
