/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.amithfernando.qrseatreservation.client.model.TableDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SeatDetail
 */
public class SeatDetailTest {
    private final SeatDetail model = new SeatDetail();

    /**
     * Model tests for SeatDetail
     */
    @Test
    public void testSeatDetail() {
        // TODO: test SeatDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'seatNo'
     */
    @Test
    public void seatNoTest() {
        // TODO: test seatNo
    }

    /**
     * Test the property 'seatStatus'
     */
    @Test
    public void seatStatusTest() {
        // TODO: test seatStatus
    }

    /**
     * Test the property 'tableDetail'
     */
    @Test
    public void tableDetailTest() {
        // TODO: test tableDetail
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'noWithStatus'
     */
    @Test
    public void noWithStatusTest() {
        // TODO: test noWithStatus
    }

    /**
     * Test the property 'unavailable'
     */
    @Test
    public void unavailableTest() {
        // TODO: test unavailable
    }

    /**
     * Test the property 'checkedIn'
     */
    @Test
    public void checkedInTest() {
        // TODO: test checkedIn
    }

    /**
     * Test the property 'reserved'
     */
    @Test
    public void reservedTest() {
        // TODO: test reserved
    }

}
