/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Setting
 */
public class SettingTest {
    private final Setting model = new Setting();

    /**
     * Model tests for Setting
     */
    @Test
    public void testSetting() {
        // TODO: test Setting
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    public void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'venue'
     */
    @Test
    public void venueTest() {
        // TODO: test venue
    }

    /**
     * Test the property 'tableSize'
     */
    @Test
    public void tableSizeTest() {
        // TODO: test tableSize
    }

    /**
     * Test the property 'seatSize'
     */
    @Test
    public void seatSizeTest() {
        // TODO: test seatSize
    }

    /**
     * Test the property 'noOfColumns'
     */
    @Test
    public void noOfColumnsTest() {
        // TODO: test noOfColumns
    }

    /**
     * Test the property 'baseImage'
     */
    @Test
    public void baseImageTest() {
        // TODO: test baseImage
    }

    /**
     * Test the property 'fontSize'
     */
    @Test
    public void fontSizeTest() {
        // TODO: test fontSize
    }

    /**
     * Test the property 'qrX'
     */
    @Test
    public void qrXTest() {
        // TODO: test qrX
    }

    /**
     * Test the property 'qrY'
     */
    @Test
    public void qrYTest() {
        // TODO: test qrY
    }

    /**
     * Test the property 'textX'
     */
    @Test
    public void textXTest() {
        // TODO: test textX
    }

    /**
     * Test the property 'textY'
     */
    @Test
    public void textYTest() {
        // TODO: test textY
    }

    /**
     * Test the property 'ticketPrefix'
     */
    @Test
    public void ticketPrefixTest() {
        // TODO: test ticketPrefix
    }

    /**
     * Test the property 'noOfDigits'
     */
    @Test
    public void noOfDigitsTest() {
        // TODO: test noOfDigits
    }

    /**
     * Test the property 'maxNoOfTickets'
     */
    @Test
    public void maxNoOfTicketsTest() {
        // TODO: test maxNoOfTickets
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

}
