/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TableDetailSummary
 */
public class TableDetailSummaryTest {
    private final TableDetailSummary model = new TableDetailSummary();

    /**
     * Model tests for TableDetailSummary
     */
    @Test
    public void testTableDetailSummary() {
        // TODO: test TableDetailSummary
    }

    /**
     * Test the property 'totalNoOfTables'
     */
    @Test
    public void totalNoOfTablesTest() {
        // TODO: test totalNoOfTables
    }

    /**
     * Test the property 'totalNoOfTotalSeats'
     */
    @Test
    public void totalNoOfTotalSeatsTest() {
        // TODO: test totalNoOfTotalSeats
    }

}
