/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.amithfernando.qrseatreservation.client.model.SeatDetail;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TableDetail
 */
public class TableDetailTest {
    private final TableDetail model = new TableDetail();

    /**
     * Model tests for TableDetail
     */
    @Test
    public void testTableDetail() {
        // TODO: test TableDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tableName'
     */
    @Test
    public void tableNameTest() {
        // TODO: test tableName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'noOfSeats'
     */
    @Test
    public void noOfSeatsTest() {
        // TODO: test noOfSeats
    }

    /**
     * Test the property 'seatDetails'
     */
    @Test
    public void seatDetailsTest() {
        // TODO: test seatDetails
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'updatedBy'
     */
    @Test
    public void updatedByTest() {
        // TODO: test updatedBy
    }

    /**
     * Test the property 'tableNoWithStatus'
     */
    @Test
    public void tableNoWithStatusTest() {
        // TODO: test tableNoWithStatus
    }

    /**
     * Test the property 'availableSeats'
     */
    @Test
    public void availableSeatsTest() {
        // TODO: test availableSeats
    }

    /**
     * Test the property 'unavailableSeats'
     */
    @Test
    public void unavailableSeatsTest() {
        // TODO: test unavailableSeats
    }

    /**
     * Test the property 'reservedSeats'
     */
    @Test
    public void reservedSeatsTest() {
        // TODO: test reservedSeats
    }

}
