/*
 * QR Seat Reservation API
 * API for managing seat reservations with QR code ticket generation
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amithfernando.qrseatreservation.client.model;

import com.amithfernando.qrseatreservation.client.model.SeatInfo;
import com.amithfernando.qrseatreservation.client.model.SellerInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TicketDetailsResponse
 */
public class TicketDetailsResponseTest {
    private final TicketDetailsResponse model = new TicketDetailsResponse();

    /**
     * Model tests for TicketDetailsResponse
     */
    @Test
    public void testTicketDetailsResponse() {
        // TODO: test TicketDetailsResponse
    }

    /**
     * Test the property 'ticketNo'
     */
    @Test
    public void ticketNoTest() {
        // TODO: test ticketNo
    }

    /**
     * Test the property 'ticketType'
     */
    @Test
    public void ticketTypeTest() {
        // TODO: test ticketType
    }

    /**
     * Test the property 'reservationStatus'
     */
    @Test
    public void reservationStatusTest() {
        // TODO: test reservationStatus
    }

    /**
     * Test the property 'canCheckIn'
     */
    @Test
    public void canCheckInTest() {
        // TODO: test canCheckIn
    }

    /**
     * Test the property 'checkInMessage'
     */
    @Test
    public void checkInMessageTest() {
        // TODO: test checkInMessage
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'seat'
     */
    @Test
    public void seatTest() {
        // TODO: test seat
    }

    /**
     * Test the property 'reservationReferenceNo'
     */
    @Test
    public void reservationReferenceNoTest() {
        // TODO: test reservationReferenceNo
    }

    /**
     * Test the property 'reservationCreatedAt'
     */
    @Test
    public void reservationCreatedAtTest() {
        // TODO: test reservationCreatedAt
    }

}
